apiVersion: kueue.x-k8s.io/v1alpha1
kind: ClusterQueue
metadata:
  name: spot-cq
spec:
  cohort: researchers
  namespaceSelector: {}
  resources:
  - name: "cpu"
    flavors:
    - name: spot
      quota:
        min: 40
  - name: "memory"
    flavors:
    - name: default
      quota:
        min: 144Gi
